[package]
name = "task"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive", "rc"] }
serde_json = "1.0.134"
uuid = { version = "1.11.0", features = ["fast-rng", "macro-diagnostics", "serde", "v4"] }
